name: Python Container Action
description: A sample Python container action
inputs:
  who-to-greet:
    description: Who to greet
    required: true
    default: World

outputs:
  greeting: 
    description: The greeting that was generated
runs:
  using: docker
  image: Dockerfile

  args:
    - ${{ inputs.who-to-greet }}
  